### ISSUE TITLE
Kossuth utcák Magyarországon kívül is vannak!

### ISSUE THREAD

**Issue by tilusnet** [sztupy/kossuth-map#2]
Ugye a megoldásod nem veszi figyelembe, hogy a referencia-pontok bárhol létezhetnek a világon?

A Kossuth-utcás példád emlékeztetett arra, hogy Magyarországon kívül is vannak ilyen helyek, történetesen egykori erdélyi nagyapám is Kossuth-utcában lakott és az a pont Magyarország keleti határától valahol 500 km-re van. Ha ezt a pontot vesszük nyerő referencia pontnak, akkor a helyes megoldásnak valahol az osztrák határon kéne lennie.

De a világon távolabb is vannak Kossuth utcák. Ez itt például az USA-beli New York államban van:
https://www.google.com/maps/place/Kossuth+St,+Rome,+NY+13440,+Egyes%C3%BClt+%C3%81llamok/@43.2179241,-75.4688907,17z/data=!3m1!4b1!4m5!3m4!1s0x89d913b981129699:0x5ea823409dbf419!8m2!3d43.217926!4d-75.4666978

**Comment by sztupy** [comment]
Ha világszinten néznénk akkor teljesen más eredmény jönne ki, de a módszer is más kell hogy legyen, mivel a jelnlegi két dimenziós síkra vetíthető méretekben működik csak. Ha lenne adatbázis a világ összes Kossuth utcájáról, akkor  esélyes, hogy Magyarországot elég lenne (többnyire) pontszerűnek kezelni, és az alapján nézni. Tippre valahol a Csendes-óceán déli részénél lenne a megoldás.
